#!/usr/bin/env python

from lib.database import Database
from lib.menu import Menu
from lib.search import Search

database = Database('vendor/xml/nesdb.xml')
menu = Menu()
search = Search(database)

catalog = None

while(catalog == None):
    input = raw_input("Search: ")
    suggestions = search.suggest(input)
    selection = menu.select_item(suggestions)
    if selection != None:
        catalog = search.get_catalog(selection)

print(catalog)
