#!/usr/bin/env python

from lib.database import Database
from lib.menu import Menu

database = Database('vendor/xml/nesdb.xml')
menu = Menu()

game = None
while(game == None):
    input = raw_input("Search for game: ")
    suggestions = database.search(input)
    selection = menu.select_item(suggestions)
    if selection != None:
        game = database.get_game_for_search_string(selection)
        
print("%s, %s" % (game.name, game.catalog))
