#!/usr/bin/env python

from lib.database import Database
from lib.search import Search


database = Database('vendor/xml/nesdb.xml')
search = Search(database)

print 'Search:',
input = raw_input()

# Sort by score then name (multiply score by -1 so we sort largest to smallest)
suggestions = sorted(search.suggest(input), key=lambda pair: (pair[1] * -1, pair[0]))

for suggestion in suggestions:
    print(suggestion[0])
